import { CalendarClock, CheckCircle2, CircleAlert, Wrench } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { maintenanceActivities, machines, parts } from "@/data/portal-data";

function statusLabel(status: string) {
	return status === "due-soon" ? "Due soon" : status.charAt(0).toUpperCase() + status.slice(1);
}

export function Maintenance({ accountId }: { accountId: string }) {
	const accountMachineIds = machines.filter((machine) => machine.accountId === accountId).map((machine) => machine.id);
	const activities = maintenanceActivities.filter((activity) => accountMachineIds.includes(activity.machineId));

	return <section className="space-y-8"><div className="space-y-2"><h1 className="text-3xl font-semibold tracking-tight">Maintenance</h1><p className="max-w-2xl text-muted-foreground">Plan equipment-related maintenance activities using the current account and machine context.</p></div><div className="grid gap-5 md:grid-cols-3"><Card><CardContent className="p-5"><CalendarClock className="size-6 text-primary" /><p className="mt-4 text-4xl font-semibold">{activities.filter((activity) => activity.status === "upcoming").length}</p><p className="text-sm text-muted-foreground">Upcoming</p></CardContent></Card><Card><CardContent className="p-5"><CircleAlert className="size-6 text-amber-600" /><p className="mt-4 text-4xl font-semibold">{activities.filter((activity) => activity.status === "due-soon" || activity.status === "overdue").length}</p><p className="text-sm text-muted-foreground">Needs attention</p></CardContent></Card><Card><CardContent className="p-5"><Wrench className="size-6 text-primary" /><p className="mt-4 text-4xl font-semibold">{activities.length}</p><p className="text-sm text-muted-foreground">Total activities</p></CardContent></Card></div><div className="space-y-4">{activities.map((activity) => { const machine = machines.find((candidate) => candidate.id === activity.machineId); return <Card key={activity.id}><CardContent className="space-y-4 p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-semibold">{activity.activity}</h2><p className="text-sm text-muted-foreground">{machine?.name} · {machine?.site}</p></div><Badge variant={activity.status === "overdue" ? "destructive" : activity.status === "due-soon" ? "outline" : "secondary"}>{statusLabel(activity.status)}</Badge></div><p className="text-sm text-muted-foreground">{activity.description}</p><div className="grid gap-3 text-sm sm:grid-cols-3"><div><p className="text-muted-foreground">Due date</p><p className="font-medium">{activity.dueDate}</p></div><div><p className="text-muted-foreground">Related parts</p><p className="font-medium">{activity.relatedPartIds.map((id) => parts.find((part) => part.id === id)?.partNumber).filter(Boolean).join(", ")}</p></div><div><p className="text-muted-foreground">Related documents</p><p className="font-medium">{activity.relatedDocumentIds.length} documents</p></div></div><Button variant="outline" size="sm" disabled={activity.status === "complete"}><CheckCircle2 className="mr-2 size-4" />View maintenance details</Button></CardContent></Card>; })}</div></section>;
}