import { ArrowRight, Bell, CircleAlert, Package, Wrench } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { accounts, machines, notifications, orders, requests } from "@/data/portal-data";

export function Dashboard({ accountId, onRouteChange }: { accountId: string; onRouteChange: (route: "equipment" | "products" | "quotes" | "support") => void }) {
  const account = accounts.find((candidate) => candidate.id === accountId) ?? accounts[0];
  const scopedMachines = machines.filter((machine) => account.machineIds.includes(machine.id));
  const scopedRequests = requests.filter((request) => request.site === account.organisation);
  const unreadNotifications = notifications.filter((notification) => !notification.read);
  const openActions = scopedRequests.filter((request) => request.status !== "complete");

  return <section className="space-y-8"><div className="space-y-2"><h1 className="text-3xl font-semibold tracking-tight">Good morning, Marek</h1></div><div className="grid gap-4 md:grid-cols-4"><Card><CardContent className="p-5"><Wrench className="size-6 text-primary" /><p className="mt-4 text-4xl font-semibold">{scopedMachines.length}</p><p className="text-sm text-muted-foreground">Machines in account</p></CardContent></Card><Card><CardContent className="p-5"><Package className="size-6 text-primary" /><p className="mt-4 text-4xl font-semibold">{orders.length}</p><p className="text-sm text-muted-foreground">Active orders</p></CardContent></Card><Card><CardContent className="p-5"><CircleAlert className="size-6 text-primary" /><p className="mt-4 text-4xl font-semibold">{openActions.length}</p><p className="text-sm text-muted-foreground">Open actions</p></CardContent></Card><Card><CardContent className="p-5"><Bell className="size-7 text-primary" /><p className="mt-4 text-4xl font-semibold">{unreadNotifications.length}</p><p className="text-sm text-muted-foreground">Unread notifications</p></CardContent></Card></div><div className="grid gap-6 lg:grid-cols-2"><Card className="bg-action-panel-color"><CardHeader><CardTitle>Outstanding actions</CardTitle></CardHeader><CardContent className="space-y-3">{openActions.map((request) => <div key={request.id} className="flex items-center justify-between gap-4 border p-4"><div><p className="text-sm font-medium">{request.subject}</p><p className="text-xs text-muted-foreground">{request.number} · {request.nextAction}</p></div><Badge variant="secondary">{request.status}</Badge></div>)}{openActions.length === 0 && <p className="text-sm text-muted-foreground">No outstanding actions.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Recent activity</CardTitle></CardHeader><CardContent className="space-y-3">{scopedRequests.map((request) => <div key={request.id} className="flex items-center justify-between gap-4 border-b py-3"><div><p className="text-sm font-medium">{request.subject}</p><p className="text-xs text-muted-foreground">{request.number} · Updated {request.updatedAt}</p></div><Badge variant="outline">{request.status}</Badge></div>)}</CardContent></Card></div><Card><CardHeader><CardTitle>Quick access</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-3"><Button onClick={() => onRouteChange("equipment")}>View equipment <ArrowRight className="ml-2 size-4" /></Button><Button variant="outline" onClick={() => onRouteChange("products")}>Find parts and services</Button><Button variant="outline" onClick={() => onRouteChange("quotes")}>View quote and order</Button><Button variant="outline" onClick={() => onRouteChange("support")}>Open support requests</Button></CardContent></Card></section>;
}
